#!/usr/bin/env bash
#Installs nginx,listening to port 80 on your web-01 and print string at root

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
