#!/usr/bin/env bash
#Installs nginx,listening to port 80 on your web-01 and print string at root
#Configures /redirect_me as a "301 Moved Permanently".
apt-get update
apt-get -y install nginx
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html
server_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://https://www.youtube.com/watch?v=QH2-TGUlwu4
                permanent;
        }
}"
echo "$server_config" > /etc/nginx/sites-available/default
service nginx restart
