#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
echo -e "Ceci n'est pas une page" > /var/www/html/custom_404.html
new_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	
	error_page 404 /custom_404.html;
	location  /custom_404.html {
            root /var/www/html/;
            internal;
	location / {
		try_files \$uri \$uri/ =404;
	}

	if (\$request_filename ~ redirect_me){
	    rewrite ^ https://https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}"

echo "$new_config" > /etc/nginx/sites-available/default

if [ "$(pgrep nginx)" -le 0 ];
then
	service nginx start
else
	service nginx restart
fi;
