#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#Make sure that HAproxy can be managed via an init script

#download haproxy
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6\*

#manage haproxy via init script
echo "ENABLED=1" >> /etc/default/haproxy

#backup configuration file
cp /etc/haproxy/haproxy.cfg{,.original}

echo "
frontend local_server 
	bind *:80
	mode http
	default_backend web-servers

backend web-servers
	balance roundrobin
	server 166918-web-01 54.144.85.149:80 check
	server 166918-web-02 18.206.202.210:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
#Installs nginx,listening to port 80 on your web-01 and print string at root
#Configures /redirect_me as a "301 Moved Permanently".
#Custom 404 error page

apt-get update
apt-get -y install nginx
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
server_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
	add_header X-Served-By \$hostname;
        location / {
                try_files \$uri \$uri/ =404;
        }
	error_page 404 /custom_404.html;
	location /custom_404 {
	  internal;
	}
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://https://www.youtube.com/watch?v=QH2-TGUlwu4
                permanent;
        }
}"
echo "$server_config" > /etc/nginx/sites-available/default
service nginx restart
