#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#Make sure that HAproxy can be managed via an init script

#download haproxy
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6\*

#manage haproxy via init script
echo "ENABLED=1" >> /etc/default/haproxy

#backup configuration file
cp /etc/haproxy/haproxy.cfg{,.original}

echo "
frontend local_server 
	bind *:80
	mode http
	default_backend web-servers

backend web-servers
	balance roundrobin
	server 166918-web-01 54.144.85.149:80 check
	server 166918-web-02 18.206.202.210:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
