#!/usr/bin/env bash
#Using your debugging skills, find out what’s keeping Ubuntu container’s
#Nginx installation from listening on port 80.
#Nginx must be running, and listening on port 80 of all the server’s active

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
