#!/usr/bin/env bash
#Using your debugging skills, find out what’s keeping Ubuntu container’s
#Nginx installation from listening on port 80.
#Nginx must be running, and listening on port 80 of all the server’s active
#IPv4 IPs

rm etc/nginx/site-enabled/default
ln -s etc/nginx/sites-available/default /etc/nginx/site-enabled/default
service nginx restart
