#!/usr/bin/env bash
#Configures ufw to block all incoming traffic except TCP ports 22(ssh),443, 80

sudo apt-get install ufw
sudo ufw status
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
