#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user.
chmod 644 /etc/nginx/nginx.conf
sed -i "li user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
